<?php

use App\BuildingLevel;
use Illuminate\Database\Seeder;

class BuildingLevelTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->insertWoodsmanHutLevels();
        $this->insertMineLevels();
        $this->insertFishingDockLevels();
        $this->insertFarmLevels();
        $this->insertAlchemistLevels();
        $this->insertMerchantLevels();
        $this->insertTownHallLevels();
    }

    private function insertWoodsmanHutLevels()
    {
        BuildingLevel::insert([
            [
                'building_id' => 1,
                'level' => 0,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 100,
                'required_stone' => 0,
                'required_gold' => 0,
                'level_town_hall' => 0,
                'power' => 0,
                'sprite' => null,
                'upgrade_duration' => 1,
            ],
            [
                'building_id' => 1,
                'level' => 1,
                'food_per_minute' => 0,
                'wood_per_minute' => 5,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 150,
                'required_stone' => 100,
                'required_gold' => 0,
                'level_town_hall' => 1,
                'power' => 10,
                'sprite' => 'woodsmanhut_1.png',
                'upgrade_duration' => 10,
            ],
            [
                'building_id' => 1,
                'level' => 2,
                'food_per_minute' => 0,
                'wood_per_minute' => 10,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 50,
                'required_wood' => 300,
                'required_stone' => 150,
                'required_gold' => 0,
                'level_town_hall' => 1,
                'power' => 20,
                'sprite' => 'woodsmanhut_1.png',
                'upgrade_duration' => 60,
            ],
            [
                'building_id' => 1,
                'level' => 3,
                'food_per_minute' => 0,
                'wood_per_minute' => 25,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 500,
                'required_wood' => 500,
                'required_stone' => 250,
                'required_gold' => 100,
                'level_town_hall' => 2,
                'power' => 50,
                'sprite' => 'woodsmanhut_1.png',
                'upgrade_duration' => 500,
            ],
            [
                'building_id' => 1,
                'level' => 4,
                'food_per_minute' => 0,
                'wood_per_minute' => 40,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 700,
                'required_wood' => 700,
                'required_stone' => 500,
                'required_gold' => 300,
                'level_town_hall' => 3,
                'power' => 60,
                'sprite' => 'woodsmanhut_1.png',
                'upgrade_duration' => 1000,
            ],
            [
                'building_id' => 1,
                'level' => 5,
                'food_per_minute' => 0,
                'wood_per_minute' => 60,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 1000,
                'required_wood' => 1000,
                'required_stone' => 700,
                'required_gold' => 700,
                'level_town_hall' => 4,
                'power' => 70,
                'sprite' => 'woodsmanhut_1.png',
                'upgrade_duration' => 1300,
            ],
            [
                'building_id' => 1,
                'level' => 6,
                'food_per_minute' => 0,
                'wood_per_minute' => 90,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 3500,
                'required_wood' => 3500,
                'required_stone' => 2000,
                'required_gold' => 2000,
                'level_town_hall' => 6,
                'power' => 100,
                'sprite' => 'woodsmanhut_1.png',
                'upgrade_duration' => 3600,
            ],
            [
                'building_id' => 1,
                'level' => 7,
                'food_per_minute' => 0,
                'wood_per_minute' => 150,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 5000,
                'required_wood' => 7000,
                'required_stone' => 4000,
                'required_gold' => 4000,
                'level_town_hall' => 7,
                'power' => 150,
                'sprite' => 'woodsmanhut_1.png',
                'upgrade_duration' => 18000,
            ],
            [
                'building_id' => 1,
                'level' => 8,
                'food_per_minute' => 0,
                'wood_per_minute' => 200,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 10000,
                'required_wood' => 10000,
                'required_stone' => 7000,
                'required_gold' => 7000,
                'level_town_hall' => 8,
                'power' => 250,
                'sprite' => 'woodsmanhut_1.png',
                'upgrade_duration' => 86400,
            ]
        ]);
    }

    private function insertMineLevels()
    {
        BuildingLevel::insert([
            [
                'building_id' => 2,
                'level' => 0,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 50,
                'required_stone' => 100,
                'required_gold' => 0,
                'level_town_hall' => 0,
                'power' => 0,
                'sprite' => null,
                'upgrade_duration' => 1,
            ],
            [
                'building_id' => 2,
                'level' => 1,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 5,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 100,
                'required_stone' => 150,
                'required_gold' => 0,
                'level_town_hall' => 1,
                'power' => 10,
                'sprite' => 'mine_1.png',
                'upgrade_duration' => 10,
            ],
            [
                'building_id' => 2,
                'level' => 2,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 10,
                'gold_per_minute' => 0,
                'required_food' => 50,
                'required_wood' => 150,
                'required_stone' => 300,
                'required_gold' => 0,
                'level_town_hall' => 1,
                'power' => 20,
                'sprite' => 'mine_1.png',
                'upgrade_duration' => 60,
            ],
            [
                'building_id' => 2,
                'level' => 3,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 15,
                'gold_per_minute' => 5,
                'required_food' => 500,
                'required_wood' => 250,
                'required_stone' => 500,
                'required_gold' => 100,
                'level_town_hall' => 2,
                'power' => 50,
                'sprite' => 'mine_1.png',
                'upgrade_duration' => 300,
            ],
            [
                'building_id' => 2,
                'level' => 4,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 40,
                'gold_per_minute' => 0,
                'required_food' => 700,
                'required_wood' => 700,
                'required_stone' => 500,
                'required_gold' => 300,
                'level_town_hall' => 3,
                'power' => 60,
                'sprite' => 'mine_1.png',
                'upgrade_duration' => 1000,
            ],
            [
                'building_id' => 2,
                'level' => 5,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 60,
                'gold_per_minute' => 0,
                'required_food' => 1000,
                'required_wood' => 1000,
                'required_stone' => 700,
                'required_gold' => 700,
                'level_town_hall' => 4,
                'power' => 70,
                'sprite' => 'mine_1.png',
                'upgrade_duration' => 1300,
            ],
            [
                'building_id' => 2,
                'level' => 6,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 90,
                'gold_per_minute' => 0,
                'required_food' => 3500,
                'required_wood' => 3500,
                'required_stone' => 2000,
                'required_gold' => 2000,
                'level_town_hall' => 6,
                'power' => 100,
                'sprite' => 'mine_1.png',
                'upgrade_duration' => 3600,
            ],
            [
                'building_id' => 2,
                'level' => 7,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 150,
                'gold_per_minute' => 0,
                'required_food' => 5000,
                'required_wood' => 7000,
                'required_stone' => 4000,
                'required_gold' => 4000,
                'level_town_hall' => 7,
                'power' => 150,
                'sprite' => 'mine_1.png',
                'upgrade_duration' => 18000,
            ],
            [
                'building_id' => 2,
                'level' => 8,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 60,
                'gold_per_minute' => 0,
                'required_food' => 1000,
                'required_wood' => 1000,
                'required_stone' => 700,
                'required_gold' => 700,
                'level_town_hall' => 8,
                'power' => 250,
                'sprite' => 'mine_1.png',
                'upgrade_duration' => 86400,
            ]
        ]);
    }

    private function insertFishingDockLevels()
    {
        BuildingLevel::insert([
            [
                'building_id' => 3,
                'level' => 0,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 200,
                'required_stone' => 100,
                'required_gold' => 0,
                'level_town_hall' => 0,
                'power' => 0,
                'sprite' => null,
                'upgrade_duration' => 1,
            ],
            [
                'building_id' => 3,
                'level' => 1,
                'food_per_minute' => 5,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 100,
                'required_stone' => 150,
                'required_gold' => 0,
                'level_town_hall' => 1,
                'power' => 10,
                'sprite' => 'fishingdock_1.png',
                'upgrade_duration' => 10,
            ],
            [
                'building_id' => 3,
                'level' => 2,
                'food_per_minute' => 10,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 100,
                'required_stone' => 150,
                'required_gold' => 0,
                'level_town_hall' => 1,
                'power' => 15,
                'sprite' => 'fishingdock_1.png',
                'upgrade_duration' => 60,
            ],
            [
                'building_id' => 3,
                'level' => 3,
                'food_per_minute' => 15,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 400,
                'required_wood' => 450,
                'required_stone' => 200,
                'required_gold' => 0,
                'level_town_hall' => 1,
                'power' => 30,
                'sprite' => 'fishingdock_1.png',
                'upgrade_duration' => 250,
            ],
            [
                'building_id' => 3,
                'level' => 4,
                'food_per_minute' => 35,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 1000,
                'required_wood' => 1000,
                'required_stone' => 400,
                'required_gold' => 0,
                'level_town_hall' => 3,
                'power' => 50,
                'sprite' => 'fishingdock_1.png',
                'upgrade_duration' => 1000,
            ],
            [
                'building_id' => 3,
                'level' => 5,
                'food_per_minute' => 50,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 3000,
                'required_wood' => 3000,
                'required_stone' => 1000,
                'required_gold' => 0,
                'level_town_hall' => 3,
                'power' => 60,
                'sprite' => 'fishingdock_1.png',
                'upgrade_duration' => 3600,
            ],
            [
                'building_id' => 3,
                'level' => 6,
                'food_per_minute' => 70,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 5000,
                'required_wood' => 5000,
                'required_stone' => 2000,
                'required_gold' => 0,
                'level_town_hall' => 5,
                'power' => 60,
                'sprite' => 'fishingdock_1.png',
                'upgrade_duration' => 3600,
            ],
            [
                'building_id' => 3,
                'level' => 7,
                'food_per_minute' => 130,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 6000,
                'required_wood' => 6000,
                'required_stone' => 4000,
                'required_gold' => 0,
                'level_town_hall' => 7,
                'power' => 100,
                'sprite' => 'fishingdock_1.png',
                'upgrade_duration' => 18000,
            ],
            [
                'building_id' => 3,
                'level' => 7,
                'food_per_minute' => 130,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 7000,
                'required_wood' => 7000,
                'required_stone' => 5000,
                'required_gold' => 0,
                'level_town_hall' => 7,
                'power' => 150,
                'sprite' => 'fishingdock_1.png',
                'upgrade_duration' => 18000,
            ],
            [
                'building_id' => 3,
                'level' => 8,
                'food_per_minute' => 160,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 9000,
                'required_wood' => 9000,
                'required_stone' => 7000,
                'required_gold' => 1000,
                'level_town_hall' => 8,
                'power' => 200,
                'sprite' => 'fishingdock_1.png',
                'upgrade_duration' => 24000,
            ]
        ]);
    }

    private function insertFarmLevels()
    {
        BuildingLevel::insert([
            [
                'building_id' => 4,
                'level' => 0,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 200,
                'required_stone' => 100,
                'required_gold' => 0,
                'level_town_hall' => 0,
                'power' => 0,
                'sprite' => null,
                'upgrade_duration' => 1,
            ],
            [
                'building_id' => 4,
                'level' => 1,
                'food_per_minute' => 15,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 200,
                'required_wood' => 250,
                'required_stone' => 300,
                'required_gold' => 0,
                'level_town_hall' => 1,
                'power' => 30,
                'sprite' => 'farm_1.png',
                'upgrade_duration' => 300,
            ],
            [
                'building_id' => 4,
                'level' => 2,
                'food_per_minute' => 30,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 1000,
                'required_wood' => 800,
                'required_stone' => 600,
                'required_gold' => 200,
                'level_town_hall' => 2,
                'power' => 50,
                'sprite' => 'farm_1.png',
                'upgrade_duration' => 600,
            ],
            [
                'building_id' => 4,
                'level' => 3,
                'food_per_minute' => 45,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 1200,
                'required_wood' => 1000,
                'required_stone' => 850,
                'required_gold' => 500,
                'level_town_hall' => 2,
                'power' => 60,
                'sprite' => 'farm_1.png',
                'upgrade_duration' => 1200,
            ],
            [
                'building_id' => 4,
                'level' => 4,
                'food_per_minute' => 65,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 2000,
                'required_wood' => 2000,
                'required_stone' => 1500,
                'required_gold' => 900,
                'level_town_hall' => 4,
                'power' => 80,
                'sprite' => 'farm_1.png',
                'upgrade_duration' => 3600,
            ],
            [
                'building_id' => 4,
                'level' => 5,
                'food_per_minute' => 85,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 3500,
                'required_wood' => 3500,
                'required_stone' => 2500,
                'required_gold' => 1500,
                'level_town_hall' => 6,
                'power' => 100,
                'sprite' => 'farm_1.png',
                'upgrade_duration' => 7200,
            ],
            [
                'building_id' => 4,
                'level' => 6,
                'food_per_minute' => 100,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 5000,
                'required_wood' => 5000,
                'required_stone' => 3500,
                'required_gold' => 3500,
                'level_town_hall' => 7,
                'power' => 130,
                'sprite' => 'farm_1.png',
                'upgrade_duration' => 21600,
            ],
            [
                'building_id' => 4,
                'level' => 7,
                'food_per_minute' => 120,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 7000,
                'required_wood' => 7000,
                'required_stone' => 5500,
                'required_gold' => 5500,
                'level_town_hall' => 7,
                'power' => 150,
                'sprite' => 'farm_1.png',
                'upgrade_duration' => 26600,
            ],
            [
                'building_id' => 4,
                'level' => 8,
                'food_per_minute' => 150,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 9000,
                'required_wood' => 9000,
                'required_stone' => 7500,
                'required_gold' => 7500,
                'level_town_hall' => 8,
                'power' => 250,
                'sprite' => 'farm_1.png',
                'upgrade_duration' => 172800,
            ]
        ]);
    }

    private function insertAlchemistLevels()
    {
        BuildingLevel::insert([
            [
                'building_id' => 5,
                'level' => 0,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 1000,
                'required_stone' => 800,
                'required_gold' => 700,
                'level_town_hall' => 2,
                'power' => 0,
                'sprite' => null,
                'upgrade_duration' => 700,
            ],
            [
                'building_id' => 5,
                'level' => 1,
                'food_per_minute' => 5,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 25,
                'required_food' => 0,
                'required_wood' => 1500,
                'required_stone' => 1200,
                'required_gold' => 1500,
                'level_town_hall' => 2,
                'power' => 50,
                'sprite' => 'alchemist_1.png',
                'upgrade_duration' => 1000,
            ],
            [
                'building_id' => 5,
                'level' => 2,
                'food_per_minute' => 15,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 35,
                'required_food' => 0,
                'required_wood' => 1500,
                'required_stone' => 1200,
                'required_gold' => 1500,
                'level_town_hall' => 2,
                'power' => 60,
                'sprite' => 'alchemist_1.png',
                'upgrade_duration' => 1500,
            ],
            [
                'building_id' => 5,
                'level' => 3,
                'food_per_minute' => 25,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 45,
                'required_food' => 500,
                'required_wood' => 2000,
                'required_stone' => 1600,
                'required_gold' => 2000,
                'level_town_hall' => 2,
                'power' => 70,
                'sprite' => 'alchemist_1.png',
                'upgrade_duration' => 1800,
            ],
            [
                'building_id' => 5,
                'level' => 4,
                'food_per_minute' => 40,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 55,
                'required_food' => 1000,
                'required_wood' => 3000,
                'required_stone' => 2600,
                'required_gold' => 4000,
                'level_town_hall' => 4,
                'power' => 80,
                'sprite' => 'alchemist_1.png',
                'upgrade_duration' => 3600,
            ],
            [
                'building_id' => 5,
                'level' => 5,
                'food_per_minute' => 50,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 60,
                'required_food' => 2000,
                'required_wood' => 5000,
                'required_stone' => 3600,
                'required_gold' => 5000,
                'level_town_hall' => 5,
                'power' => 100,
                'sprite' => 'alchemist_1.png',
                'upgrade_duration' => 10800,
            ],
            [
                'building_id' => 5,
                'level' => 6,
                'food_per_minute' => 60,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 80,
                'required_food' => 4000,
                'required_wood' => 5000,
                'required_stone' => 4600,
                'required_gold' => 6000,
                'level_town_hall' => 6,
                'power' => 120,
                'sprite' => 'alchemist_1.png',
                'upgrade_duration' => 10800,
            ],
            [
                'building_id' => 5,
                'level' => 7,
                'food_per_minute' => 70,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 90,
                'required_food' => 8000,
                'required_wood' => 8000,
                'required_stone' => 4600,
                'required_gold' => 7000,
                'level_town_hall' => 7,
                'power' => 140,
                'sprite' => 'alchemist_1.png',
                'upgrade_duration' => 86400,
            ],
            [
                'building_id' => 5,
                'level' => 8,
                'food_per_minute' => 100,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 100,
                'required_food' => 10000,
                'required_wood' => 10000,
                'required_stone' => 8600,
                'required_gold' => 8000,
                'level_town_hall' => 8,
                'power' => 200,
                'sprite' => 'alchemist_1.png',
                'upgrade_duration' => 172800,
            ]
        ]);
    }

    private function insertMerchantLevels()
    {
        BuildingLevel::insert([
            [
                'building_id' => 6,
                'level' => 0,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 300,
                'required_wood' => 300,
                'required_stone' => 300,
                'required_gold' => 0,
                'level_town_hall' => 0,
                'power' => 30,
                'sprite' => null,
                'upgrade_duration' => 900,
            ],
            [
                'building_id' => 6,
                'level' => 1,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 10,
                'required_food' => 500,
                'required_wood' => 500,
                'required_stone' => 500,
                'required_gold' => 100,
                'level_town_hall' => 1,
                'power' => 10,
                'sprite' => 'merchant_1.png',
                'upgrade_duration' => 1200,
            ],
            [
                'building_id' => 6,
                'level' => 2,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 25,
                'required_food' => 1000,
                'required_wood' => 1000,
                'required_stone' => 1000,
                'required_gold' => 1000,
                'level_town_hall' => 2,
                'power' => 30,
                'sprite' => 'merchant_1.png',
                'upgrade_duration' => 1600,
            ],
            [
                'building_id' => 6,
                'level' => 3,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 40,
                'required_food' => 1300,
                'required_wood' => 1300,
                'required_stone' => 1300,
                'required_gold' => 1300,
                'level_town_hall' => 2,
                'power' => 50,
                'sprite' => 'merchant_1.png',
                'upgrade_duration' => 1800,
            ],
            [
                'building_id' => 6,
                'level' => 4,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 65,
                'required_food' => 1000,
                'required_wood' => 3000,
                'required_stone' => 2600,
                'required_gold' => 4000,
                'level_town_hall' => 4,
                'power' => 80,
                'sprite' => 'merchant_1.png',
                'upgrade_duration' => 3600,
            ],
            [
                'building_id' => 6,
                'level' => 5,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 70,
                'required_food' => 2000,
                'required_wood' => 5000,
                'required_stone' => 3600,
                'required_gold' => 5000,
                'level_town_hall' => 5,
                'power' => 100,
                'sprite' => 'merchant_1.png',
                'upgrade_duration' => 10800,
            ],
            [
                'building_id' => 6,
                'level' => 6,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 90,
                'required_food' => 4000,
                'required_wood' => 5000,
                'required_stone' => 4600,
                'required_gold' => 6000,
                'level_town_hall' => 6,
                'power' => 120,
                'sprite' => 'merchant_1.png',
                'upgrade_duration' => 10800,
            ],
            [
                'building_id' => 6,
                'level' => 7,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 95,
                'required_food' => 5000,
                'required_wood' => 6000,
                'required_stone' => 4600,
                'required_gold' => 7000,
                'level_town_hall' => 6,
                'power' => 140,
                'sprite' => 'merchant_1.png',
                'upgrade_duration' => 86400,
            ],
            [
                'building_id' => 6,
                'level' => 8,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 120,
                'required_food' => 10000,
                'required_wood' => 10000,
                'required_stone' => 8600,
                'required_gold' => 8000,
                'level_town_hall' => 8,
                'power' => 200,
                'sprite' => 'merchant_1.png',
                'upgrade_duration' => 172800,
            ]
        ]);
    }

    private function insertTownHallLevels()
    {
        BuildingLevel::insert([
            [
                'building_id' => 7,
                'level' => 0,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 0,
                'required_wood' => 200,
                'required_stone' => 200,
                'required_gold' => 0,
                'level_town_hall' => 0,
                'power' => 0,
                'sprite' => null,
                'upgrade_duration' => 60,
            ],
            [
                'building_id' => 7,
                'level' => 1,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 300,
                'required_wood' => 600,
                'required_stone' => 600,
                'required_gold' => 300,
                'level_town_hall' => 1,
                'power' => 10,
                'sprite' => 'townhall_1.png',
                'upgrade_duration' => 1000,
            ],
            [
                'building_id' => 7,
                'level' => 2,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 1000,
                'required_wood' => 1500,
                'required_stone' => 1500,
                'required_gold' => 1000,
                'level_town_hall' => 2,
                'power' => 50,
                'sprite' => 'townhall_1.png',
                'upgrade_duration' => 3600,
            ],
            [
                'building_id' => 7,
                'level' => 3,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 3000,
                'required_wood' => 3000,
                'required_stone' => 3000,
                'required_gold' => 3000,
                'level_town_hall' => 3,
                'power' => 100,
                'sprite' => 'townhall_1.png',
                'upgrade_duration' => 21600,
            ],
            [
                'building_id' => 7,
                'level' => 4,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 6000,
                'required_wood' => 6000,
                'required_stone' => 6000,
                'required_gold' => 6000,
                'level_town_hall' => 4,
                'power' => 200,
                'sprite' => 'townhall_1.png',
                'upgrade_duration' => 43200,
            ],
            [
                'building_id' => 7,
                'level' => 5,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 10000,
                'required_wood' => 10000,
                'required_stone' => 10000,
                'required_gold' => 10000,
                'level_town_hall' => 5,
                'power' => 300,
                'sprite' => 'townhall_1.png',
                'upgrade_duration' => 86400,
            ],
            [
                'building_id' => 7,
                'level' => 6,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 15000,
                'required_wood' => 15000,
                'required_stone' => 15000,
                'required_gold' => 15000,
                'level_town_hall' => 6,
                'power' => 450,
                'sprite' => 'townhall_1.png',
                'upgrade_duration' => 172800,
            ],
            [
                'building_id' => 7,
                'level' => 7,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 20000,
                'required_wood' => 20000,
                'required_stone' => 20000,
                'required_gold' => 20000,
                'level_town_hall' => 7,
                'power' => 600,
                'sprite' => 'townhall_1.png',
                'upgrade_duration' => 345600,
            ],
            [
                'building_id' => 7,
                'level' => 8,
                'food_per_minute' => 0,
                'wood_per_minute' => 0,
                'stone_per_minute' => 0,
                'gold_per_minute' => 0,
                'required_food' => 40000,
                'required_wood' => 40000,
                'required_stone' => 40000,
                'required_gold' => 40000,
                'level_town_hall' => 8,
                'power' => 1000,
                'sprite' => 'townhall_1.png',
                'upgrade_duration' => 604800,
            ]
        ]);
    }
}
